hztoggle: Added wlr-randr support

diff --git a/hztoggle b/hztoggle
--- a/hztoggle
+++ b/hztoggle
@@ -13,12 +13,33 @@ m2_width="$m1_width"
 m2_height="$m1_height"
 
 toggle-cosmic () {
+    if ! [[ -x "$(command -v cosmic-randr)" ]]; then
+	echo "cosmic-randr not found!"
+	exit 1
+    fi
+
     case "$cmd" in
 	"1")
 	    cosmic-randr mode "$display" "$m1_width" "$m1_height" --refresh "$m1_hertz"
 	    ;;
 	"2")
 	    cosmic-randr mode "$display" "$m2_width" "$m2_height" --refresh "$m2_hertz"	
+	    ;;
+    esac
+}
+
+toggle-wlr () {
+    if ! [[ -x "$(command -v wlr-randr)" ]]; then
+	echo "wlr-randr not found!"
+	exit 1
+    fi
+
+    case "$cmd" in
+	"1")
+	    wlr-randr --output "$display" --mode "${m1_width}x${m1_height}@${m1_hertz}"
+	    ;;
+	"2")
+	    wlr-randr --output "$display" --mode "${m2_width}x${m2_height}@${m2_hertz}"
 	    ;;
     esac
 }
@@ -36,10 +57,11 @@ info () {
 
 case "$backend" in
     "cosmic")
-	if ! [[ -x "$(command -v cosmic-randr)" ]]; then
-	    echo "cosmic-randr not found!"
-	    exit 1
-	fi
 	toggle-cosmic
 	info
+	;;
+    "wlr")
+	toggle-wlr
+	info
+	;;
 esac
