hztoggle: Added kscreen-doctor support

diff --git a/hztoggle b/hztoggle
--- a/hztoggle
+++ b/hztoggle
@@ -44,6 +44,23 @@ toggle-wlr () {
     esac
 }
 
+toggle-kscreen () {
+    if ! [[ -x "$(command -v kscreen-doctor)" ]]; then
+	echo "kscreen-doctor not found!"
+	exit 1
+    fi
+
+    case "$cmd" in
+	"1")
+	    kscreen-doctor "output.${display}.mode.${m1_width}x${m1_height}@${m1_hertz}"
+	    ;;
+	"2")
+	    kscreen-doctor "output.${display}.mode.${m2_width}x${m2_height}@${m2_hertz}"
+	    ;;
+    esac
+
+}
+
 info () {
     case "$cmd" in
 	"1")
@@ -51,6 +68,9 @@ info () {
 	    ;;
 	"2")
 	    echo "Display $display ($backend) set to $m2_width px x $m2_height px @ $m2_hertz Hz"
+	    ;;
+	*)
+	    echo "Mode $cmd not recognized. Default modes are 1 and 2."
 	    ;;
     esac
 }
@@ -63,5 +83,12 @@ case "$backend" in
     "wlr")
 	toggle-wlr
 	info
+	;;
+    "kscreen")
+	toggle-kscreen
+	info
+	;;
+    *)
+	echo "Unrecognized backend $backend. Please use cosmic, wlr or kscreen."
 	;;
 esac
